# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c7c6da4395d6b3ce5604bc2b9b13a7dd1c5b2a0e79b342506be0950ae922ef7e8bd0c247bd3858505139d0cd3bdbd7c95907c2202370cec9b454679fd34c9eeb

test:
  secret_key_base: e38df69129948dd949fdabc74dc8496b4f5d310d559126e653aca33ea851920f4c7fd36135e14983674ce88823dcad8ed8423298bf5fc891a51e119a801e380f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
